version: "3.9"

services:

  frontend:
    image: nginx
    ports:
      - "3000:80"

  backend:
    image: nginx

  worker:
    image: nginx

  db:
    image: postgres
    environment:
      POSTGRES_DB: pulso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
